[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.tokenizer", "composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php artisan migrate --force ; php artisan db:seed --force ; mkdir -p storage/app/documents storage/framework/cache storage/framework/sessions storage/framework/views storage/logs ; chmod -R 777 storage bootstrap/cache ; php -S 0.0.0.0:$PORT -t public/"
