[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --include=dev && npm install -g serve"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "serve dist -l tcp://0.0.0.0:$PORT --single"
